# Default values for vaultwarden.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vaultwarden/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

smtp:
  enabled: true
  host: smtp.domain.tld
  from: info@your.tld
  ssl: true
  port: "587"
  username: username
  password: password


# This example show the configuration using zalando postgres operator. But it can be replaced with any other db / secret.
database:
  secretName: "vault.vaultcluster.credentials"
  host: "vault-postgres-cluster"
  port: "5432"
  name: "vault"

backups:
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 500Mi
      cpu: 1
  enabled: false
  s3AccessKey: "key"
  s3AccessSecret: "secret"
  s3Bucket: "upsource_backup"
  s3Region: "region"
  s3Endpoint: "backup.s3.com"
  s3v4: "" # Set to yes to use a v4 signature. Note: you must use v4 to upload in some regions, like eu-central-1
  s3Prefix: ""
  s3Encrypt: ""
  schedule: "0 0 0 * * *"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
   limits:
     cpu: 500m
     memory: 1Gi
   requests:
     cpu: 500m
     memory: 1Gi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  config:
    size: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
