apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teamcity.fullname" . }}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "teamcity.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "teamcity.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 13001
        {{if .Values.podSecurityContext }}
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        {{- end }}
      containers:
        {{- if .Values.backups.enabled }}
        - name: {{ .Chart.Name }}-backups
          image: danieldenktmit/docker-tar-backup-s3:v0.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.backups.s3AccessKey }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.backups.s3AccessSecret }}
            - name: S3_BUCKET
              value: {{ .Values.backups.s3Bucket }}
            - name: S3_REGION
              value: {{ .Values.backups.s3Region }}
            - name: S3_ENDPOINT
              value: {{ .Values.backups.s3Endpoint }}
            - name: S3_S3V4
              value: {{ .Values.backups.s3v4 | quote }}
            - name: S3_PREFIX
              value: {{ .Values.backups.s3Prefix | quote }}
            - name: S3_ENCRYPT
              value: {{ .Values.backups.s3Encrypt | quote }}
            - name: SCHEDULE
              value: {{ .Values.backups.schedule }}
            - name: FILES_TO_BACKUP
              value: "/data/teamcity_server/datadir"
            - name: BACKUP_FILE_NAME_SUFFIX
              value: "teamcity"
          resources:
            {{- toYaml .Values.backups.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data/teamcity_server/datadir
              name: data
        {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8111
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            timeoutSeconds: 30
            initialDelaySeconds: 60
            httpGet:
              path: /login.html
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - mountPath: /data/teamcity_server/datadir
              name: data
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "teamcity.fullname" . }}-data
        {{- end }}
